sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t satyarth406/docker-react .

script:
  - docker run -e CI=true satyarth406/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-185603236399"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
